# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.digitalocean.com/automaticsolutions
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
  host: automaticsolutions.ru

pvc:
  accessModes:
    - ReadWriteMany
  storage: 1Gi
  storageClassName: csi-s3
  existingClaim: ''

db:
  host: ''

smtp:
  host: ''
  port: ''
  user: ''
  pass: ''
  from: ''
  name: ''
  debug: ''

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
