# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.digitalocean.com/automaticsolutions
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
  host: automaticsolutions.ru

pvc:
  storage: 1Gi
  storageClassName: csi-s3

envinronments:
  - name: MAIL_HOST
    value: ''
  - name: MAIL_PORT
    value: ''
  - name: MAIL_USER
    value: ''
  - name: MAIL_PASSWORD
    value: ''

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
