apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry}}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_NAME
              value: {{ include "wordpress.fullname" . | quote }}
            - name: DB_USER
              value: {{ include "wordpress.fullname" . | quote }}
            - name: DB_PASSWORD
              value: {{ include "wordpress.fullname" . | quote }}
            - name: SMTP_USER
              value: {{ .Values.smtp.user | quote }}
            - name: SMTP_PASS
              value: {{ .Values.smtp.pass | quote }}
            - name: SMTP_HOST
              value: {{ .Values.smtp.host | quote }}
            - name: SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: SMTP_FROM
              value: {{ .Values.smtp.from | quote }}
            - name: SMTP_NAME
              value: {{ .Values.smtp.name | quote }}
            - name: SMTP_SECURE
              value: "tls"
            - name: SMTP_AUTH
              value: 'true'
            - name: SMTP_DEBUG
              value: {{ .Values.smtp.debug | quote }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: /wp-login.php
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: /wp-login.php
              port: http
          {{- end }}
          volumeMounts:
            - name: "{{ include "wordpress.fullname" . }}-volume"
              mountPath: "/var/www/html/wp-content/uploads"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "wordpress.fullname" . }}-volume
          persistentVolumeClaim:
            {{- if eq .Values.pvc.existingClaim "" }}
            claimName: {{ include "wordpress.fullname" . }}
            {{- else }}
            claimName: {{ .Values.pvc.existingClaim }}
            {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
