# Default values for nodejs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.digitalocean.com/automaticsolutions
  repository: nodejs
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  host: automaticsolutions.ru

resources:
  requests:
    memory: 512Mi
    cpu: 300m

nodeSelector: {}

tolerations: []

affinity: {}
